/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BProgress: typeof import('bootstrap-vue-next/components/BProgress')['BProgress']
    BtnAudio: typeof import('./src/components/buttons/BtnAudio.vue')['default']
    BtnGithub: typeof import('./src/components/buttons/BtnGithub.vue')['default']
    BtnInstall: typeof import('./src/components/buttons/BtnInstall.vue')['default']
    BtnNotification: typeof import('./src/components/buttons/BtnNotification.vue')['default']
    BtnReset: typeof import('./src/components/buttons/BtnReset.vue')['default']
    BtnUpdateApp: typeof import('./src/components/buttons/BtnUpdateApp.vue')['default']
    BtnVibrate: typeof import('./src/components/buttons/BtnVibrate.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    QButton: typeof import('./src/components/QButton.vue')['default']
    QuizCard: typeof import('./src/components/QuizCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuccessCheckMark: typeof import('./src/components/SuccessCheckMark.vue')['default']
    SymbolBuiltName: typeof import('./src/components/SymbolBuiltName.vue')['default']
  }
}
